---
title: "EDA"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(psych)
library(ggplot2)
```

#Read Data
```{r}
diabetes <- read_csv("diabetes_binary_health_indicators_BRFSS2015.csv")

#convert col names to lower case for easy reference
colnames(diabetes) <- tolower(colnames(diabetes))
```

#Create Factors
```{r}
diabetes <- diabetes |>
  mutate(
    diabetes_binary_f = factor(diabetes_binary, levels = c(0,1),
                               labels = c("no diabetes", "diabetes")), 
    highbp_f = factor(highbp, levels = c(0,1),
                               labels = c("no high BP", "high BP")),
    highchol_f = factor(highchol, levels = c(0,1),
                               labels = c("no high cholesterol", "high cholesterol")),
    cholcheck_f = factor(cholcheck, levels = c(0,1),
                               labels = c("no cholesterol check in 5 years", "yes cholesterol check in 5 years")),
    smoker_f = factor(smoker, levels = c(0,1),
                               labels = c("no", "yes")), 
    stroke_f = factor(stroke, levels = c(0,1),
                               labels = c("no", "yes")),
    heartdiseaseorattack_f = factor(heartdiseaseorattack, levels = c(0,1),
                               labels = c("no", "yes")),
    physactivity_f = factor(physactivity, levels = c(0,1),
                               labels = c("no", "yes")),
    fruits_f = factor(fruits, levels = c(0,1),
                               labels = c("no","yes")),
    veggies_f = factor(veggies, levels = c(0,1),
                               labels = c("no", "yes")),
    hvyalcoholconsump_f = factor(hvyalcoholconsump, levels = c(0,1),
                               labels = c("no", "yes")),
    anyhealthcare_f = factor(anyhealthcare, levels = c(0,1),
                               labels = c("no", "yes")),
    nodocbccost_f = factor(nodocbccost, levels = c(0,1),
                               labels = c("no","yes")),
    genhlth_f = factor(genhlth, levels = 1:5,
                               labels = c("excellent", "very good", "good", "fair", "poor")),
    diffwalk_f  = factor(diffwalk, levels = c(0,1),
                               labels = c("no", "yes")),
    sex_f = factor(sex, levels = c(0,1),
                               labels = c("female", "male")),
    age_f = factor(age, levels = 1:13,
                        labels = c("18 to 24",
                          "25 to 29", 
                          "30 to 34", 
                          "35 to 39",
                          "40 to 44",
                          "45 to 49",
                          "50 to 54",
                          "55 to 59",
                          "60 to 64",
                          "65 to 69",
                          "70 to 74",
                          "75 to 79", 
                          "80 to high"
                   )),
    education_f = factor(education, levels = 1:6,
                         labels = c("Never attended school or only kindergarten",
                         "Grades 1 through 8 (Elementary)",
                         "Grades 9 through 11 (Some high school)",
                         "Grade 12 or GED (High school graduate)",
                         "College 1 year to 3 years (Some college or technical school)",
                         "College 4 years or more (College graduate)")
                         ),
    income_f = factor(income, levels = 1:8,
                      labels = c("< 10k",
                                "< 15k",
                                "< 20k",
                                "< 25k",
                                "< 35k",
                                "< 50k",
                                "< 75k",
                                "75k+"))
  )
```

# EDA


## Missing Values

There are no missing values for any variable including new factor variables.

```{r}

# write function to count NAs in a column
sum_na <- function(column) {
  sum(is.na(column))
}

# operate function across all dataset columns

na_counts <- diabetes |>
  summarize(across(everything(), sum_na))
na_counts
```


```{r}
#diabetes status by income 
diabetes |>
  group_by(income_f, diabetes_binary_f) |>
  summarize(count = n()) |>
  pivot_wider(names_from = diabetes_binary_f, values_from = count)
```



```{r}
#diabetes status by income 
diabetes |>
  group_by(age_f, income_f) |>
  summarize(count = n()) |>
  pivot_wider(names_from = income_f, values_from = count)

#distribution of age by income
#evident higher income is more common between middle-age
ggplot(diabetes, aes(x = age_f , fill = income_f)) + 
  geom_bar() +
  labs(title = "Distribution of Age and Income", x = "Age Category", y = "Observations") +
  theme(plot.title = element_text(hjust = 0.5),
    legend.position = "top", legend.box = "horizontal") +
  scale_fill_discrete(guide = guide_legend(nrow=1))

```

```{r}

# diabetes prevalence tables
diabetes |>
  group_by(sex_f) |>
  summarize(PrevalencePer1000 = (sum(diabetes_binary == 1)/n()*1000)) |>
  arrange(desc(PrevalencePer1000))

diabetes |>
  group_by(income_f) |>
  summarize(PrevalencePer1000 = (sum(diabetes_binary == 1)/n()*1000)) |>
  arrange(desc(PrevalencePer1000))

diabetes |>
  group_by(hvyalcoholconsump_f) |>
  summarize(PrevalencePer1000 = (sum(diabetes_binary == 1)/n()*1000)) |>
  arrange(desc(PrevalencePer1000))

#view proportion of heavy drinkers by income level and sex
alc_inc_df <- diabetes |>
  group_by(income_f, sex_f) |>
  summarize(PrevalencePer1000 = (sum(hvyalcoholconsump == 1)/n()*1000))

ggplot(alc_inc_df, aes(x = income_f , y = PrevalencePer1000, fill = sex_f)) + 
  geom_bar(stat = "identity") +
  labs(title = "Heavy Drinking Rate by Income and Sex", x = "Income Level", y = "Incidence of Heavy Drinking (per 1000)") +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "top", legend.box = "horizontal") +
  scale_fill_discrete(guide = guide_legend(nrow=1))


diabetes |>
  group_by(age_f) |>
  summarize(PrevalencePer1000 = (sum(diabetes_binary == 1)/n()*1000)) |>
  arrange(desc(PrevalencePer1000))

# two way contingency table of prevalence by high blood pressure and high cholesterol
diabetes |>
  group_by(highbp_f, highchol_f) |>
  summarize(PrevalencePer1000 = (sum(diabetes_binary == 1)/n()*1000)) |>
  arrange(desc(PrevalencePer1000)) |>
  pivot_wider(names_from = highchol_f, values_from = PrevalencePer1000)

# two way contingency table of prevalence across mental health and physical health levels
diabetes |>
  group_by(smoker_f, hvyalcoholconsump_f) |>
  summarize(PrevalencePer1000 = (sum(diabetes_binary == 1)/n()*1000)) |>
  arrange(desc(PrevalencePer1000)) |>
  pivot_wider(names_from = smoker_f, values_from = PrevalencePer1000)
```

